import axios from "axios";
import Head from "next/head";
import { useState } from "react";

type Song = {
  title: string;
  author: string;
  pagePath: string;
  isCasual: boolean;
};

export default function Top() {
  const [songs, setSongs] = useState<Song[]>([]);

  const generate = async () => {
    const data = await axios.get("/api/generate");
    console.log(data.data);
    console.log("type", typeof data.data);
    const object = JSON.parse(data.data);
    console.log("オブジェクト", object);
    setSongs([...object]);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Topページ</h1>
        <button onClick={generate}>generateボタン</button>
        {songs.length > 0 &&
          songs.map((song, index) => (
            <div key={index}>
              <p>{song.title}</p>
              <p>{song.author}</p>
              <a href={song.pagePath}>{song.pagePath}</a>
              <p>{song.isCasual ? "カジュアル" : "クラシック"}</p>
              <iframe
                width="560"
                height="315"
                src={song.pagePath.replace("watch?v=", "embed/")}
                title={song.title}
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowFullScreen
              ></iframe>
            </div>
          ))}
      </main>
    </>
  );
}
